# Generated by Django 5.2.8 on 2025-11-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_requestlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("ingredient", "Ingredient"), ("packaging", "Packaging")],
                max_length=20,
            ),
        ),
    ]
